title: RMLawal
author: Rabiu Lawal
email: lawwalee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Hi, I'm Lawal. I'm a Software Developer.
 I also do digital and graphics design. 
 I am a lone ranger currently, an artisan of some sort, freelancing if you get my drift.
# social links
github_username:  https://github.com/MRLawal

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
